services:
  - type: web
    name: news-prediction-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn dashboard:app"
    branch: main
    autoDeploy: true
